### PR TITLE
docs: new maintainer

### PR DESCRIPTION
**Pull request by slint**
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

### CODE REVIEW

**Comment by lnielsen** [comment]
LGTM

**Comment by jirikuncar** [comment]
Shall we disable self-approvals? https://github.com/inveniosoftware/invenio-csl-rest/blob/master/.lgtm#L3

**Comment by slint** [comment]
@jirikuncar I think it would make more sense for repositories with 2 or less number of maintainers to have self-approvals enabled, to minimize risk of the "LGTM-block" phenomenon, in case of a maintainer not being available.

**Comment by jirikuncar** [comment]
> - in case there are several other co-maintainers for the given package,
>   the same PR can be used to change the LGTM settings to have
>   `self_approval_off = true`.

I'm just following on previous email from @tiborsimko in mailing list.

**Pull request merged**
